version = 0.1

[default.deploy.parameters]
stack_name = "thanks-card"
resolve_s3 = true
s3_prefix = "thanks-card"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StackFamily=\"thanks-card\""
image_repositories = []
